# Generated by Django 2.2.27 on 2022-03-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('case_name', models.CharField(max_length=200)),
                ('execution_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='testcaserun',
            name='TestRun_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.TestRun'),
        ),
    ]
