# Generated by Django 2.2.27 on 2022-03-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20220324_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCaseRun',
        ),
    ]
