# Generated by Django 2.2.27 on 2022-03-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_delete_testcaserun'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseRun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('case_name', models.CharField(max_length=200)),
                ('execution_time', models.DateTimeField()),
                ('TestRun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.TestRun')),
            ],
        ),
    ]
