# Generated by Django 2.2.27 on 2022-03-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_testcaserun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcaserun',
            name='execution_time',
        ),
    ]
