# Generated by Django 2.2.27 on 2022-03-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_testcaserun_execution_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcaserun',
            old_name='TestRun_id',
            new_name='TestRun',
        ),
    ]
