# Generated by Django 2.2.27 on 2022-03-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20220325_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcaserun',
            old_name='TestRun',
            new_name='test_run',
        ),
    ]
