# Generated by Django 2.2.27 on 2022-03-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20220325_0751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCaseRun',
        ),
        migrations.DeleteModel(
            name='TestRun',
        ),
    ]
