# Generated by Django 2.2.27 on 2022-03-25 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_testcaserun_testrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaserun',
            name='execution_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
