# Generated by Django 2.2.27 on 2022-03-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_testcaserun_execution_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCaseRun',
        ),
        migrations.DeleteModel(
            name='TestRun',
        ),
    ]
