# Generated by Django 2.2.27 on 2022-03-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_testcaserun_testrun'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCaseRun',
        ),
        migrations.DeleteModel(
            name='TestRun',
        ),
    ]
