# Generated by Django 2.2.27 on 2022-03-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0013_auto_20220328_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('test_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.TestLine')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseRun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('case_name', models.CharField(max_length=200)),
                ('execution_time', models.DateTimeField()),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.TestRun')),
            ],
        ),
    ]
