# Generated by Django 2.2.27 on 2022-04-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
