# Generated by Django 2.2.27 on 2022-04-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='test_line',
        ),
        migrations.DeleteModel(
            name='TestCaseRun',
        ),
        migrations.DeleteModel(
            name='TestLine',
        ),
        migrations.DeleteModel(
            name='TestRun',
        ),
    ]
