# Generated by Django 2.2.27 on 2022-04-07 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0018_testcaserun_testline_testrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='testline',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
