# Generated by Django 2.2.27 on 2022-04-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_testline_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCaseRun',
            new_name='TestCase',
        ),
    ]
